### ISSUE TITLE
Error 1053:The service did not respond to the start or control request in a timely fashion when trying to install service

### ISSUE THREAD

**Issue by rafaela-bernardelli** [PeterKottas/DotNetCore.WindowsService#32]
Hi, @PeterKottas.

When I try to execute the command dotnet <my_service>.dll action:install, the following error occurs:

Exception: System.ComponentModel.Win32Exception: O serviço não respondeu à requisição de início ou controle em tempo hábil
   at DasMulli.Win32.ServiceUtils.ServiceHandle.Start()
   at DasMulli.Win32.ServiceUtils.Win32ServiceManager.CreateService(String serviceName, String displayName, String description, String binaryPath, Win32ServiceCredentials credentials, Boolean autoStart, Boolean startImmediately, ErrorSeverity errorSeverity)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Install(HostConfiguration`1 config, ServiceController sc, Int32 counter)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.UsingServiceController(HostConfiguration`1 config, Action`2 action)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Run(Action`1 runAction).

Can you help me?
Tks.
Rafaela.

**Comment by dmitry-pavlov** [comment]
I experience the same issue. On English version of Windows is sounds like:  **The service did not respond to the start or control request in a timely fashion**

```
System.ComponentModel.Win32Exception (0x80004005): The service did not respond to the start or control request in a timely fashion
   at DasMulli.Win32.ServiceUtils.ServiceHandle.Start()
   at DasMulli.Win32.ServiceUtils.Win32ServiceManager.CreateService(String serviceName, String displayName, String description, String binaryPath, Win32ServiceCredentials credentials, Boolean autoStart, Boolean startImmediately, ErrorSeverity errorSeverity)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Install(HostConfiguration`1 config, ServiceController sc, Int32 counter)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.UsingServiceController(HostConfiguration`1 config, Action`2 action)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Run(Action`1 runAction)
```

It happens when service is installed and attempts to start. If you try then start again but via Windows system Services application it shows: **Error 1053: "The service did not respond in a timely fashion"**

I tried to find the fix for this. Tried to increase ServicesPipeTimeout as described [here](http://support.threattracksecurity.com/support/solutions/articles/1000071019-error-1053-the-service-did-not-respond-in-a-timely-fashion-when-attempting-to-start-stop-or-pause) - it didn't help.

@PeterKottas it is kind of super urgent and important. If I won't be able to fix this in a day or so - I will have to find alternatives to DotNetCore.WindowsService. Please propose the fix, provide your thoughts. Thank you in advance!

**Comment by rafaela-bernardelli** [comment]
I tried the same solution, @dmitry-pavlov (increase ServicesPipeTimeout in regedit), but it did not work for me either.

**Comment by PeterKottas** [comment]
Hi guys yep no worries, I can attempt to help you out. The first and obvious thing would be to try some of these : [previous cases of this problem in issues](https://github.com/PeterKottas/DotNetCore.WindowsService/search?q=The+service+did+not+respond+to+the+start+or+control+request+in+a+timely+fashion&type=Issues&utf8=%E2%9C%93) Give that a go. I am fairly certain that you will be able to solve it with that. 
If not, then clone this repo, try the example and see if that works. (It should) If it does, then it should be straight forward to work out the difference. Let me know how it goes. Happy coding and gl!

**Comment by rafaela-bernardelli** [comment]
![image](https://user-images.githubusercontent.com/11426099/28668424-105bf254-72a6-11e7-9b7e-a4cc67977d90.png)
With your example the same error occurs. I'm thinking it's a problem with my Windows, but I have not been able to solve it yet, or even guess what the cause is. Could it be something with antivirus?

**Comment by PeterKottas** [comment]
I assume it says something along the lines of "Service couldn't start on the local computer" right? Could you try to run t as administrator?

**Comment by rafaela-bernardelli** [comment]
I am running the command prompt as an administrator, look:
![image](https://user-images.githubusercontent.com/11426099/28670793-9dd8143c-72b0-11e7-8678-3202b279fad0.png)

**Comment by PeterKottas** [comment]
Do you have visual studio 2017 installed?

If so, can you pull down the source, open it. Then debug the example
project and add the parameter action:install ?


Peter Kottas

Check out great tips for bargain holidays on
https://facebook.com/tipsforholiday

**Comment by rafaela-bernardelli** [comment]
Debuging, the result is access denied, as shown in the image below.
**StackTrace**:
   at DasMulli.Win32.ServiceUtils.ServiceControlManager.Connect(INativeInterop nativeInterop, String machineName, String databaseName, ServiceControlManagerAccessRights desiredAccessRights)
   at DasMulli.Win32.ServiceUtils.Win32ServiceManager.CreateService(String serviceName, String displayName, String description, String binaryPath, Win32ServiceCredentials credentials, Boolean autoStart, Boolean startImmediately, ErrorSeverity errorSeverity)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Install(HostConfiguration`1 config, ServiceController sc, Int32 counter) in C:\Projetos\PeterKottas-DotNetCore.WindowsService\Source\PeterKottas.DotNetCore.WindowsService\ServiceRunner.cs:line 181

![image](https://user-images.githubusercontent.com/11426099/28682702-50b3e572-72d4-11e7-81fc-589fdebf5ec9.png)

**Comment by dmitry-pavlov** [comment]
I have converted my windows service into old kind .NET 4.6.1 win service project, which uses the logic from Standard 2.0 class library. The approach similar to what is described [here](https://stackify.com/creating-net-core-windows-services/).
