### ISSUE TITLE
Service does not start

### ISSUE THREAD

**Issue by saxmaster79** [PeterKottas/DotNetCore.WindowsService#71]
My application runs as normal app, but not as windows service. Neither from Visual Studio nor from the published files.

2018-01-29 13:31:37,073 [DataHubMain] ERROR RemecDataHub.Program - Service RemecDataHub.SchedulerService errored with exception : Der Dienst antwortete nicht rechtzeitig auf die Start- oder Steuerungsanforderung - System.ComponentModel.Win32Exception (0x80004005): Der Dienst antwortete nicht rechtzeitig auf die Start- oder Steuerungsanforderung
   at DasMulli.Win32.ServiceUtils.ServiceHandle.Start()
   at DasMulli.Win32.ServiceUtils.Win32ServiceManager.CreateService(String serviceName, String displayName, String description, String binaryPath, Win32ServiceCredentials credentials, Boolean autoStart, Boolean startImmediately, ErrorSeverity errorSeverity)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Install(HostConfiguration`1 config, ServiceController sc, Int32 counter)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.UsingServiceController(HostConfiguration`1 config, Action`2 action)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Run(Action`1 runAction)

**Comment by PeterKottas** [comment]
I guess you are not starting it as administrator, which you should
