### ISSUE TITLE
service == null in OnStop method

### ISSUE THREAD

**Issue by stawr93** [PeterKottas/DotNetCore.WindowsService#89]
Hi,
I was trying to use your library and faced some strange issue: service is null in OnStop callback action.
Consider following code:

```
public class WinService : IMicroService
{
    private readonly IMicroServiceController _controller;
    private SomeService _someService;

    public WinService()
    {
    }

    public WinService(IMicroServiceController controller)
    {
        _controller = controller;
    }

    public void Start()
    {
        _someService = new SomeService();
    }

    public void Stop()
    {
        _someService.Dispose();
        _controller?.Stop();
    }
}

class Program
{
    static void Main(string[] args)
    {
        ServiceRunner<WinService>.Run(config =>
        {
            config.SetName("SomeService");
            config.SetDisplayName("Some Service");
            config.Service(serviceConfig =>
            {
                serviceConfig.ServiceFactory((extraArgs, controller) => new WinService(controller));
                serviceConfig.OnStart((service, extraArgs) => service.Start());
                serviceConfig.OnStop(service => service.Stop());
                serviceConfig.OnError(e =>
                {
                    Console.WriteLine("Service errored with exception : {0}\n{1}", e.Message, e.StackTrace);
                });
            });
        });
    }
}
```

So now, we can build it and then run and stop the service:

```
PS C:\Projects\SomeService> dotnet run action:start
Successfully started service "SomeService" ("No description")
PS C:\Projects\SomeService> dotnet run action:stop
Successfully stopped service "SomeService" ("No description")
Service errored with exception : Object reference not set to an instance of an object.
   at SomeService.Program.<>c.<Main>b__0_4(DgsWinService service) in C:\Projects\SomeService\Program.cs:line 18
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.StopService(HostConfiguration`1 config, ServiceController sc)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.UsingServiceController(HostConfiguration`1 config, Action`2 action)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Run(Action`1 runAction)
```

At first look I can see HostConfiguration.Service is not filled in case of any command except action:run and action:run-interactive.
How can I perform some action before service being stopped?

**Comment by stawr93** [comment]
I tested example from repo and got the same error. Seems like a bug

**Comment by PeterKottas** [comment]
Thanks for finding this problems, I'll take a look at it now and hopefully fix the problem.

**Comment by PeterKottas** [comment]
Fixed by https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v2.0.7. Feel free to reopen if you find any issues with the current solution.
